### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by nabyendu** [DominoKit/domino-ui-rest-mvp4g2-sample#1]
Hi
Unable to find jar safehtml-1.0-SNAPSHOT.jar
Below is error detail:
Downloading from oss-sonatype: https://oss.sonatype.org/content/repositories/google-snapshots/org/gwtproject/safehtml/safehtml/1.0-SNAPSHOT/safehtml-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:02 min
[INFO] Finished at: 2019-05-28T10:28:56+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dominoUiMvpRestSample: Could not resolve dependencies for project com.sample:dominoUiMvpRestSample:gwt-app:1.0.0-SNAPSHOT: Could not find artifact org.gwtproject.safehtml:safehtml:jar:1.0-SNAPSHOT in sonatype-snapshots-repo (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

Thanks in advance

Regards,
Nabyendu

**Comment by vegegoku** [comment]
This project have not been updated for some time, it was due to old elemento-core dependency, now it is fixed please try  again.
and thanks for reporting

**Comment by nabyendu** [comment]
Thank you, it working now.
